---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.domainName }}
  namespace: searchcombat
  labels:
    environment: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.domainName }}
      secretName: {{ .Values.domainName }}
  rules:
    - host: {{ .Values.domainName }}
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: happysmile
                port:
                  number: 80
